[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=/tmp/supervisord.log
logfile_maxbytes=5MB
logfile_backups=3
loglevel=error
pidfile=/tmp/supervisord.pid
nodaemon=false
midfds=1024
minprocs=200
user=root
childlogdir=/tmp/

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:amf_web]
command = python run.py
directory = /app
stdout_logfile = /tmp/amf_web.log
stderr_logfile = /tmp/amf_web_err.log

[program:amf_consumer]
command = python amfconsumer.py
directory = /app
strout_logfile = /tmp/amf_consumer.log
strerr_logfile = /tmp/amf_consumer_err.log

